services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "1000"
    command: npm run dev -- --hostname 0.0.0.0